from pathlib import Path
R=Path(__file__).resolve().parents[1]
projects=(R/'remake/project-source.html').read_text().replace('Explore the actual work.','Try the work.').replace('Three public repositories. Open a source receipt, try a workspace simulation, or follow a review decision. Each example tells you exactly what was checked.','Three repositories. Three different ways to inspect the work.')
reading=(R/'remake/reading-source.html').read_text().replace('<details id="reading"','<details id="reading"').replace('Read the three fictional stories','Full stories & source records')
resume=(R/'stage/incumbent-resume-source.html').read_text()
def character(name,state='idle',cls='',label=''):
 return f'<img class="character {cls}" data-character="{name}" data-pose="{state}" src="characters/{name}/frames/{state}/frame-000.png" width="256" height="320" alt="{label}" decoding="async">'
header=f'''<a class="skip" href="#resume" data-nav="resume">Skip to résumé</a><header class="masthead"><a class="name" href="#home" data-nav="home">Cayleb<span>Alvarez-James</span></a><button class="guide-toggle" aria-expanded="false" aria-controls="guide">{character('mofu')}<span>Meet Mofu</span></button><label class="mode"><input id="mode" type="checkbox" checked aria-label="Explore mode"><span class="mode-surface"><span>Explore</span><span>Professional</span><i></i></span></label></header>
<aside id="guide" hidden aria-label="Mofu guide"><button class="close-guide" aria-label="Close Mofu guide">×</button>{character('mofu','greeting')}<h2>A hand with the next step.</h2><p>Choose a workday, inspect the records, then see the decision a person reviews.</p><nav><a href="#story" data-nav="story">Workday examples ↗</a><a href="#projects" data-nav="projects">Real project evidence ↗</a><a href="#resume" data-nav="resume">My résumé ↗</a></nav><button id="motion-toggle" aria-pressed="false">Pause ambient motion</button><small>Your system’s reduced-motion preference is respected separately.</small></aside>'''
hero=f'''<section id="home" class="opening" aria-labelledby="home-title"><div class="opening-copy"><p class="eyebrow">Personal AI · freelance consulting</p><h1 id="home-title" tabindex="-1">AI that fits<br><em>your work.</em></h1><p class="lead">I learn the job. Build your assistant.<br>Help your team make it useful.</p><div class="opening-actions"><a class="primary" href="#story" data-nav="story">Try a workday <span>↗</span></a><a href="#resume" data-nav="resume">Résumé ↗</a></div></div><div class="opening-art" aria-label="Mofu, your guide to the workday examples"><div class="light-pool"></div><div class="loop-chip chip-work">Your work</div><div class="loop-chip chip-draft">A useful draft</div><div class="loop-chip chip-review">Your decision <span>✓</span></div><button class="hero-mofu" aria-label="Ask Mofu for guidance">{character('mofu',label='Mofu, a translucent glass droplet')}</button><span class="mofu-caption">A little help. You stay in charge.</span></div><nav class="question-choices" aria-label="Choose a workday">'''+''.join(f'''<button data-start="{c}">{character(c)}<span><small>{role}</small><strong>{question}</strong></span><b aria-hidden="true">↗</b></button>''' for c,role,question in [('pip','Pip · repairs','When can it be picked up?'),('folio','Folio · editorial','Is this proof approved?'),('loam','Loam · stock','What can we promise?')])+'''</nav></section>'''
story=f'''<details class="section-shell story-shell" id="story-shell" open><summary><span>01</span> A workday, with an assistant <b>↗</b></summary><section id="story" aria-labelledby="story-title"><div id="story-journey"><div class="story-pin"><header class="story-top"><nav class="assistant-picker" aria-label="Choose an assistant">'''+''.join(f'<button data-chapter="{c}" aria-pressed="{str(c=="pip").lower()}">{character(c)}<span>{name}</span></button>' for c,name in [('pip','Pip'),('folio','Folio'),('loam','Loam')])+'''</nav><span class="fiction-label">Fictional workday · nothing is sent</span></header><div class="story-scene"><div class="story-heading"><p id="role-label" class="eyebrow">Tessa · repairs</p><h2 id="story-title" tabindex="-1">When can it<br><em>be picked up?</em></h2><p id="story-line">A part is missing. A customer needs a date.</p></div><div class="record-art"><div class="glass-record record-a"><span id="record-a-label">Part SW-17</span><strong id="record-a-value">Not received</strong><small id="record-a-note">Workshop record</small></div><div class="glass-record record-b"><span id="record-b-label">Pickup date</span><strong id="record-b-value">Unconfirmed</strong><small id="record-b-note">Receipt + testing first</small></div><div class="check-bridge" aria-hidden="true"><i></i><i></i><i></i></div><div class="review-pill"><span id="decision-label">Tessa reviews the next step</span><span aria-hidden="true">↗</span></div></div><figure class="assistant-art">'''+character('pip',cls='story-character',label='Pip, a glass bean-shaped assistant')+'''<figcaption id="assistant-caption">Pip · repair coordination</figcaption></figure></div><footer class="story-controls"><button class="round-back" data-action="back" aria-label="Previous story step" disabled>←</button><nav class="step-picker" aria-label="Story steps"><button data-beat="0" aria-pressed="true">The task</button><button data-beat="1" aria-pressed="false">The check</button><button data-beat="2" aria-pressed="false">Your decision</button></nav><button class="primary" data-action="next">Check the record <span>→</span></button></footer><div class="story-bottom"><span class="scroll-note">Scroll to follow the workday</span><details id="record-detail"><summary>Why this decision?</summary><p id="source-detail"></p><a id="story-source" href="stage/sources/repair-fiction.json">Inspect source records ↗</a></details></div></div></div></section></details>'''
services='''<details class="section-shell service-shell" id="service-shell"><summary><span>03</span> How we would work together <b>↗</b></summary><section id="services"><h2>Learn. Build. Keep it useful.</h2><div class="service-steps"><details><summary>Learn the job</summary><p>Observe real tasks, conversations and follow-through—typically around three days per person, with discovery scope agreed first.</p></details><details><summary>Build around it</summary><p>Plan a personal Manus assistant around phone and desktop work. Choose and approve integrations around the tools each employee uses.</p></details><details><summary>Help it stick</summary><p>Train the team and maintain approved integrations as tools and work change. Scope and review boundaries are agreed together.</p></details></div><a class="primary" href="mailto:caylebalvarezjames@gmail.com">Discuss your workflow ↗</a></section></details>'''
footer='''<footer class="site-footer"><span>Connecticut · independent developer</span><a href="mailto:caylebalvarezjames@gmail.com">Let’s talk ↗</a><details><summary>Sources & artwork</summary><p>Characters are the user-approved Mofu, Pip, Folio and Loam runtime artwork, used unchanged. Fictional story records are source-linked. Project evidence is dated. Glass surfaces and motion are original code by Sol; artwork is 2D, not a rigged 3D model.</p><a href="characters/verification.json">Asset provenance</a></details></footer>'''
(R/'index.html').write_text('''<!doctype html><html lang="en" data-mode="explore"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Cayleb Alvarez-James develops personal AI assistants around your work. Try source-backed examples and explore documented projects."><title>Cayleb · AI that fits your work</title><link rel="stylesheet" href="remake/site.css?v=1"><script src="vendor/gsap-3.14.2.min.js" defer></script><script type="module" src="remake/site.js?v=1"></script></head><body>'''+header+'<main>'+hero+story+reading+'<details class="section-shell projects-shell" id="projects-shell" open><summary><span>02</span> Try the actual projects <b>↗</b></summary>'+projects+'</details>'+services+resume+'</main>'+footer+'</body></html>')
print('Built new character-led composition with preserved evidence and exact résumé fragment.')

import runpy
runpy.run_path(str(R/"scripts/enhance-remake.py"))
